//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chat_client.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chat_client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this software.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App language.
        /// </summary>
        internal static string AppLanguageLabel {
            get {
                return ResourceManager.GetString("AppLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a number between 1000 and 65535..
        /// </summary>
        internal static string ChooseAnAppropriatePortNumber {
            get {
                return ResourceManager.GetString("ChooseAnAppropriatePortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client socket is not connected..
        /// </summary>
        internal static string ClientSocketNotConnected {
            get {
                return ResourceManager.GetString("ClientSocketNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --about             Opens the About window
        ///  --debug, -d         Opens debug console at startup
        ///  --username, -u      Sets username and auto-connects to localhost
        ///  --port, -p          Sets server port (default: 7123)
        ///  --theme, -t         Sets theme (light or dark)
        ///  --dark              Shortcut for dark theme
        ///  --light             Shortcut for light theme
        ///  --language, -l      Sets UI language (en or fr)
        ///  --encrypted, -e     Enables message encryption
        ///  --reduceInTray, -r  Minimizes to tray on [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string CliHelpText {
            get {
                return ResourceManager.GetString("CliHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command Line Help.
        /// </summary>
        internal static string CliHelpTitle {
            get {
                return ResourceManager.GetString("CliHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client command-Line options:.
        /// </summary>
        internal static string CliOptionsHelpLine1 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --help, -h, -?                Show this help message.
        /// </summary>
        internal static string CliOptionsHelpLine10 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --username, -u, -user         Set username and auto-connect to localhost.
        /// </summary>
        internal static string CliOptionsHelpLine2 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --port, -p                    Set server port (default: 7123).
        /// </summary>
        internal static string CliOptionsHelpLine3 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --theme, -t, --dark, --light Apply UI theme.
        /// </summary>
        internal static string CliOptionsHelpLine4 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --language, -l, --lang        Set UI language (en or fr).
        /// </summary>
        internal static string CliOptionsHelpLine5 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --encrypted, -e               Enable message encryption.
        /// </summary>
        internal static string CliOptionsHelpLine6 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --reduceInTray, -r, --reduce Minimize to tray on startup.
        /// </summary>
        internal static string CliOptionsHelpLine7 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --debug, -d                   Show debug console.
        /// </summary>
        internal static string CliOptionsHelpLine8 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   --about                       Show About window.
        /// </summary>
        internal static string CliOptionsHelpLine9 {
            get {
                return ResourceManager.GetString("CliOptionsHelpLine9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command-line arguments.
        /// </summary>
        internal static string CommandLineArguments {
            get {
                return ResourceManager.GetString("CommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect.
        /// </summary>
        internal static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed..
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Decryption failed].
        /// </summary>
        internal static string DecryptionFailed {
            get {
                return ResourceManager.GetString("DecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect.
        /// </summary>
        internal static string DisconnectButton {
            get {
                return ResourceManager.GetString("DisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect error.
        /// </summary>
        internal static string DisconnectError {
            get {
                return ResourceManager.GetString("DisconnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message encryption enabled..
        /// </summary>
        internal static string EncryptionEnabled {
            get {
                return ResourceManager.GetString("EncryptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must be connected to the server to enable encryption..
        /// </summary>
        internal static string EncryptionRequiresConnection {
            get {
                return ResourceManager.GetString("EncryptionRequiresConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption could not be activated..
        /// </summary>
        internal static string ErrorInActivatingEncryption {
            get {
                return ResourceManager.GetString("ErrorInActivatingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while loading settings. Please check your theme resources..
        /// </summary>
        internal static string ErrorLoadingThemeResources {
            get {
                return ResourceManager.GetString("ErrorLoadingThemeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while disconnecting : .
        /// </summary>
        internal static string ErrorWhileDisconnecting {
            get {
                return ResourceManager.GetString("ErrorWhileDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting missing keys....
        /// </summary>
        internal static string GettingMissingKeys {
            get {
                return ResourceManager.GetString("GettingMissingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has connected.
        /// </summary>
        internal static string HasConnected {
            get {
                return ResourceManager.GetString("HasConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has disconnected.
        /// </summary>
        internal static string HasDisconnected {
            get {
                return ResourceManager.GetString("HasDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid public key. Encryption was not enabled..
        /// </summary>
        internal static string InvalidPublicKey {
            get {
                return ResourceManager.GetString("InvalidPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The IP address is incorrect. Leave it blank to connect locally..
        /// </summary>
        internal static string IPAddressInvalid {
            get {
                return ResourceManager.GetString("IPAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  v1.0 - sept. 2025 - Laurent Barraud .
        /// </summary>
        internal static string LicenceFinal {
            get {
                return ResourceManager.GetString("LicenceFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This software is for education purposes only and is provided &quot;as is&quot;,\nwithout any kind of warranty..
        /// </summary>
        internal static string LicenceInfo1 {
            get {
                return ResourceManager.GetString("LicenceInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In no event shall the author be liable for any indirect, incidental\nor consequential damages, including loss of data, lost profits, o\nbusiness interruption with the use of this software..
        /// </summary>
        internal static string LicenceInfo2 {
            get {
                return ResourceManager.GetString("LicenceInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Button images inspired by resources available on Flaticon.com..
        /// </summary>
        internal static string LicenceInfoResources {
            get {
                return ResourceManager.GetString("LicenceInfoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Error : Your message failed to send.].
        /// </summary>
        internal static string MessageSendingFailed {
            get {
                return ResourceManager.GetString("MessageSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port number is not valid..
        /// </summary>
        internal static string PortNumberInvalid {
            get {
                return ResourceManager.GetString("PortNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port number is valid..
        /// </summary>
        internal static string PortNumberValid {
            get {
                return ResourceManager.GetString("PortNumberValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The public key was rejected by the server. Encryption was not enabled..
        /// </summary>
        internal static string PublicKeyRejected {
            get {
                return ResourceManager.GetString("PublicKeyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce in system tray.
        /// </summary>
        internal static string ReduceToTrayLabel {
            get {
                return ResourceManager.GetString("ReduceToTrayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll left.
        /// </summary>
        internal static string ScrollLeft {
            get {
                return ResourceManager.GetString("ScrollLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll right.
        /// </summary>
        internal static string ScrollRight {
            get {
                return ResourceManager.GetString("ScrollRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to send the public RSA key to the server. Please check your connection..
        /// </summary>
        internal static string SendingClientsPublicRSAKeyToTheServerFailed {
            get {
                return ResourceManager.GetString("SendingClientsPublicRSAKeyToTheServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to send message..
        /// </summary>
        internal static string SendingFailed {
            get {
                return ResourceManager.GetString("SendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending public key....
        /// </summary>
        internal static string SendingPublicKey {
            get {
                return ResourceManager.GetString("SendingPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server has closed. You will be disconnected shortly....
        /// </summary>
        internal static string ServerHasClosed {
            get {
                return ResourceManager.GetString("ServerHasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The server is unreachable or has refused the connection..
        /// </summary>
        internal static string ServerUnreachable {
            get {
                return ResourceManager.GetString("ServerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        internal static string TrayOpen {
            get {
                return ResourceManager.GetString("TrayOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        internal static string TrayQuit {
            get {
                return ResourceManager.GetString("TrayQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use custom TCP port.
        /// </summary>
        internal static string UseCustomPortLabel {
            get {
                return ResourceManager.GetString("UseCustomPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use encryption for messages.
        /// </summary>
        internal static string UseEncryptionLabel {
            get {
                return ResourceManager.GetString("UseEncryptionLabel", resourceCulture);
            }
        }
    }
}
