//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chat_client.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("chat_client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this software.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à App language.
        /// </summary>
        public static string AppLanguageLabel {
            get {
                return ResourceManager.GetString("AppLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a number between 1000 and 65535..
        /// </summary>
        public static string ChooseAnAppropriatePortNumber {
            get {
                return ResourceManager.GetString("ChooseAnAppropriatePortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client socket is not connected..
        /// </summary>
        public static string ClientSocketNotConnected {
            get {
                return ResourceManager.GetString("ClientSocketNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Usage: chat-client.exe [options]
        ///
        ///Options:
        ///  -u, --username        Set your username and auto-connect
        ///  -p, --port                Set the server port
        ///
        ///   --dark, --light        Switch to theme
        ///
        ///  --en, --english       Switch to English
        ///  --fr, --french          Switch to French
        ///
        ///  -e, --encrypted       Enable end-to-end encryption
        ///
        ///  -r, -t, -m, --reduce  Start minimized to system tray
        ///  --tray, --min
        ///
        ///  -c, -d, --debug       Open console window
        ///                   
        ///  -h, -? , --help        [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string CliOptionsHelpText {
            get {
                return ResourceManager.GetString("CliOptionsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command Line Help.
        /// </summary>
        public static string CliOptionsHelpTitle {
            get {
                return ResourceManager.GetString("CliOptionsHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Command-line arguments.
        /// </summary>
        public static string CommandLineArguments {
            get {
                return ResourceManager.GetString("CommandLineArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed..
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Decryption failed].
        /// </summary>
        public static string DecryptionFailed {
            get {
                return ResourceManager.GetString("DecryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect error.
        /// </summary>
        public static string DisconnectError {
            get {
                return ResourceManager.GetString("DisconnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message encryption enabled..
        /// </summary>
        public static string EncryptionEnabled {
            get {
                return ResourceManager.GetString("EncryptionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must be connected to the server to enable encryption..
        /// </summary>
        public static string EncryptionRequiresConnection {
            get {
                return ResourceManager.GetString("EncryptionRequiresConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption could not be activated..
        /// </summary>
        public static string ErrorInActivatingEncryption {
            get {
                return ResourceManager.GetString("ErrorInActivatingEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while loading settings. Please check your theme resources..
        /// </summary>
        public static string ErrorLoadingThemeResources {
            get {
                return ResourceManager.GetString("ErrorLoadingThemeResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while disconnecting : .
        /// </summary>
        public static string ErrorWhileDisconnecting {
            get {
                return ResourceManager.GetString("ErrorWhileDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Getting missing keys....
        /// </summary>
        public static string GettingMissingKeys {
            get {
                return ResourceManager.GetString("GettingMissingKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has connected.
        /// </summary>
        public static string HasConnected {
            get {
                return ResourceManager.GetString("HasConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à has disconnected.
        /// </summary>
        public static string HasDisconnected {
            get {
                return ResourceManager.GetString("HasDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid public key. Encryption was not enabled..
        /// </summary>
        public static string InvalidPublicKey {
            get {
                return ResourceManager.GetString("InvalidPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The IP address is incorrect. Leave it blank to connect locally..
        /// </summary>
        public static string IPAddressInvalid {
            get {
                return ResourceManager.GetString("IPAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  v1.0 - oct. 2025 - Laurent Barraud .
        /// </summary>
        public static string LicenceFinal {
            get {
                return ResourceManager.GetString("LicenceFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This software is provided &quot;as is&quot;, without any kind of warranty..
        /// </summary>
        public static string LicenceInfo1 {
            get {
                return ResourceManager.GetString("LicenceInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In no event shall the author be liable for any indirect, incidental or consequential damages, including loss of data, lost profits, or business interruption with the use of this software..
        /// </summary>
        public static string LicenceInfo2 {
            get {
                return ResourceManager.GetString("LicenceInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Button images inspired by resources available on Flaticon.com..
        /// </summary>
        public static string LicenceInfoResources {
            get {
                return ResourceManager.GetString("LicenceInfoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à [Error : Your message failed to send.].
        /// </summary>
        public static string MessageSendingFailed {
            get {
                return ResourceManager.GetString("MessageSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port number is not valid..
        /// </summary>
        public static string PortNumberInvalid {
            get {
                return ResourceManager.GetString("PortNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port number is valid..
        /// </summary>
        public static string PortNumberValid {
            get {
                return ResourceManager.GetString("PortNumberValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The public key was rejected by the server. Encryption was not enabled..
        /// </summary>
        public static string PublicKeyRejected {
            get {
                return ResourceManager.GetString("PublicKeyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reduce in system tray.
        /// </summary>
        public static string ReduceToTrayLabel {
            get {
                return ResourceManager.GetString("ReduceToTrayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll left.
        /// </summary>
        public static string ScrollLeft {
            get {
                return ResourceManager.GetString("ScrollLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll right.
        /// </summary>
        public static string ScrollRight {
            get {
                return ResourceManager.GetString("ScrollRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to send the public RSA key to the server. Please check your connection..
        /// </summary>
        public static string SendingClientsPublicRSAKeyToTheServerFailed {
            get {
                return ResourceManager.GetString("SendingClientsPublicRSAKeyToTheServerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to send message..
        /// </summary>
        public static string SendingFailed {
            get {
                return ResourceManager.GetString("SendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sending public key....
        /// </summary>
        public static string SendingPublicKey {
            get {
                return ResourceManager.GetString("SendingPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server has closed. You will be disconnected shortly....
        /// </summary>
        public static string ServerHasClosed {
            get {
                return ResourceManager.GetString("ServerHasClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The server is unreachable or has refused the connection..
        /// </summary>
        public static string ServerUnreachable {
            get {
                return ResourceManager.GetString("ServerUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open.
        /// </summary>
        public static string TrayOpen {
            get {
                return ResourceManager.GetString("TrayOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string TrayQuit {
            get {
                return ResourceManager.GetString("TrayQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use custom TCP port.
        /// </summary>
        public static string UseCustomPortLabel {
            get {
                return ResourceManager.GetString("UseCustomPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use encryption for messages.
        /// </summary>
        public static string UseEncryptionLabel {
            get {
                return ResourceManager.GetString("UseEncryptionLabel", resourceCulture);
            }
        }
    }
}
